I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 241, in script call
    call race  # race 1
  File "game/race.rpy", line 70, in script call
    call f1630 # should this be jump instead
  File "game/race.rpy", line 738, in script call
    call f11500
  File "game/race.rpy", line 863, in script
    if lowTime < LT[curCar]:
  File "game/race.rpy", line 863, in <module>
    if lowTime < LT[curCar]:
NameError: name 'LT' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 241, in script call
    call race  # race 1
  File "game/race.rpy", line 70, in script call
    call f1630 # should this be jump instead
  File "game/race.rpy", line 738, in script call
    call f11500
  File "game/race.rpy", line 863, in script
    if lowTime < LT[curCar]:
  File "renpy/ast.py", line 1852, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2249, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2242, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/race.rpy", line 863, in <module>
    if lowTime < LT[curCar]:
NameError: name 'LT' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.4.1439
Engine Work Needed 1.0
Mon May 24 17:29:49 2021
